# environment for TID project
sudo /emr/notebook-env/bin/pip install "colorama>=0.3.8"
sudo /emr/notebook-env/bin/pip install "empiricaldist==0.3.9"
sudo /emr/notebook-env/bin/pip install "future==0.18.2"
sudo /emr/notebook-env/bin/pip install "h2o==3.30.1.3"
sudo /emr/notebook-env/bin/pip install "ipympl==0.5.8"
sudo /emr/notebook-env/bin/pip install "ipykernel==5.1.4"
sudo /emr/notebook-env/bin/pip install "nodejs==0.1.1"
sudo /emr/notebook-env/bin/pip install "pyod==0.8.3"
sudo /emr/notebook-env/bin/pip install "pyarrow==1.0.1"
sudo /emr/notebook-env/bin/pip install "s3fs==0.5.1"
sudo /emr/notebook-env/bin/pip install "seaborn==0.11.0"
sudo /emr/notebook-env/bin/pip install "shap==0.36.0"
sudo /emr/notebook-env/bin/pip install "tabulate==0.8.7"
