sudo /emr/notebook-env/bin/pip install "colorama>=0.3.8"
sudo /emr/notebook-env/bin/pip install empiricaldist
sudo /emr/notebook-env/bin/pip install future
sudo /emr/notebook-env/bin/pip install h2o
sudo /emr/notebook-env/bin/pip install ipympl
sudo /emr/notebook-env/bin/pip install nodejs
sudo /emr/notebook-env/bin/pip install pyod
sudo /emr/notebook-env/bin/pip install pyarrow
sudo /emr/notebook-env/bin/pip install s3fs
sudo /emr/notebook-env/bin/pip install seaborn
sudo /emr/notebook-env/bin/pip install shap
sudo /emr/notebook-env/bin/pip install tabulate
