CREATE ROLE "READONLY" COMMENT = 'A custom role called READONLY that only has the ability to read data';
GRANT ROLE "READONLY" TO ROLE "SYSADMIN";
GRANT ROLE "READONLY" TO USER usernamehere;

GRANT USAGE 
  ON WAREHOUSE COMPUTE_WH 
  TO ROLE READONLY;

GRANT USAGE 
  ON DATABASE DATABASENAMEHERE
  TO ROLE READONLY;
  
GRANT USAGE
  ON SCHEMA DATABASENAMEHERE.SCHEMANAMEHERE
  TO ROLE READONLY;
  
GRANT SELECT ON ALL TABLES IN SCHEMA DATABASENAMEHERE.SCHEMANAMEHERE TO ROLE READONLY;
GRANT SELECT ON ALL VIEWS IN SCHEMA DATABASENAMEHERE.SCHEMANAMEHERE TO ROLE READONLY;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DATABASENAMEHERE.SCHEMANAMEHERE TO ROLE READONLY;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DATABASENAMEHERE.SCHEMANAMEHERE TO ROLE READONLY;
